"""Generate docs/QUERIES.md from the SQL headers (single source of truth: the .sql files)."""
from __future__ import annotations

from src.generate.config import ROOT

from .sqlio import catalog

TITLES = {"ddl": "DDL", "staging": "Staging to core loads", "marts": "Marts (views)", "analysis": "Analysis and reconstructed extractions"}


def render() -> str:
    cat = catalog()
    out = ["# Query catalog (SYNTHETIC data)", "",
           "Generated by `python -m src.pipeline.catalog` from the header comment of every file in [`sql/`](../sql). One file per query. "
           "\"Replaces\" names the original notebook analysis (generic labels: *notebook 1* = paid-acquisition funnel, *notebook 2* = usage "
           "concentration / Pareto, *notebook 3* = free-user analysis) that the query supersedes; queries of kind **reconstructed** rebuild, "
           "against the core tables, the extraction that would have produced an original input dataset.", "",
           f"{len(cat)} files. The dashboard page *Queries & schema* shows the SQL text of each.", ""]
    for g in ["ddl", "staging", "marts", "analysis"]:
        rows = [q for q in cat if q["folder"] == g]
        out += [f"## {TITLES[g]}", "", "| Id | Business question | Tables | Grain | Replaces / kind | File |", "|---|---|---|---|---|---|"]
        for q in rows:
            rep = q.get("replaces", "") + (" (reconstructed)" if q.get("kind") == "reconstructed" else "")
            esc = lambda t: (t or "").replace("|", "\\|")  # noqa: E731
            out.append(f"| {q['id']} | {esc(q.get('business_question'))} | {esc(q.get('tables'))} | {esc(q.get('grain'))} | {esc(rep)} | [{q['path'].split('/', 1)[1]}](../{q['path']}) |")
        out.append("")
    return "\n".join(out)


def main() -> None:
    (ROOT / "docs" / "QUERIES.md").write_text(render(), encoding="utf-8")
    print("wrote docs/QUERIES.md")


if __name__ == "__main__":
    main()
